<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'ByJG\\PHPThread\\' => array($vendorDir . '/byjg/phpthread/src'),
    'ByJG\\Cache\\' => array($vendorDir . '/byjg/cache-engine/src'),
);
